FROM vllm/vllm-openai:latest

# ENV MODEL_NAME=microsoft/Phi-4-mini-instruct \
#     VLLM_ALLOW_RUNTIME_LORA_UPDATING=true

ENV MODEL_NAME=microsoft/Phi-4-mini-instruct

ENTRYPOINT python3 -m vllm.entrypoints.openai.api_server --model $MODEL_NAME $VLLM_ARGS